# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: check-morti

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

# The `functions` block defines what code to deploy
functions:
  checkmorti:
    handler: index.checkMorti
    timeout: 20 # default is 6
    # The `events` block defines how to trigger the handler code
    events:
      - schedule: rate(3 hours)
